=== vishnu1002/ws-codes/product/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="items" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="phName" type="xs:string"></xs:element>
                            <xs:element name="price" type="xs:float"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== vishnu1002/ws-codes/product/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="items.xsd">
    <items>
        <phName>Galaxy S22</phName>
        <price>899.99</price>
    </items>
    <items>
        <phName>iPhone 13 Pro</phName>
        <price>999.99</price>
    </items>
    <items>
        <phName>OnePlus 10 Pro</phName>
        <price>899.00</price>
    </items>
    <items>
        <phName>Google Pixel 7</phName>
        <price>799.00</price>
    </items>
    <items>
        <phName>Xiaomi Mi 12</phName>
        <price>899.00</price>
    </items>
</products>
